arm_shoulder_pan_joint_controller:
	controller:
		package: dynamixel_controllers
		module: joint_position_controller
		type: JointPositionController
		joint_name: arm_shoulder_pan_joint
		joint_speed: 0.1
	motor:
		id: 1
		init: 2048
		min: 320
		max: 3823

arm_shoulder_lift_joint_controller:
	controller:
		package: dynamixel_controllers
		module: joint_position_controller
		type: JointPositionController
		joint_name: arm_shoulder_lift_joint
		joint_speed: 0.1
	motor:
		id: 2
		init: 2048
		min: 320
		max: 3823

arm_elbow_flex_joint_controller:
	controller:
		package: dynamixel_controllers
		module: joint_position_controller
		type: JointPositionController
		joint_name: arm_elbow_flex_joint
		joint_speed: 0.1
	motor:
		id: 3
		init: 2048
		min: 320
		max: 3823

arm_wrist_flex_joint_controller:
	controller:
		package: dynamixel_controllers
		module: joint_position_controller
		type: JointPositionController
		joint_name: arm_wrist_flex_joint
		joint_speed: 0.1
	motor:
		id: 4
		init: 2048
		min: 320
		max: 3823

gripper_link_joint_controller:
	controller:
		package: dynamixel_controllers
		module: joint_position_controller
		type: JointPositionController
		joint_name: gripper_link_joint
		joint_speed: 0.1
	motor:
		id: 5
		init: 2048
		min: 320
		max: 3823
